CREATE DATABASE IF NOT EXISTS users;

USE users;

CREATE TABLE admins (
    id INT(11) NOT NULL AUTO_INCREMENT,
    name VARCHAR(25) DEFAULT NULL,
    lastname VARCHAR(25) DEFAULT NULL,
    username VARCHAR(25) DEFAULT NULL,
    email VARCHAR(255),
    password VARCHAR(255),
    role ENUM('admin', 'editor'), 
    ADD CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    ADD UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(),
    PRIMARY KEY (id)
);

CREATE TABLE articles (
    id INT(11) NOT NULL AUTO_INCREMENT,
    title VARCHAR(100) NOT NULL,
    article VARCHAR(2500) NOT NULL,
    ADD CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    ADD UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(),
    PRIMARY KEY (id)
);

CREATE TABLE profiles (
    id INT(11) NOT NULL AUTO_INCREMENT,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    username VARCHAR(2500) NOT NULL,
    ADD CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    ADD UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(),
    PRIMARY KEY (id)
);


-- ALTER TABLE articless
-- ADD CONSTRAINT FK_article_admins FOREIGN KEY (articleID)
-- REFERENCES admins (ID);
